services:
  db:
    image: postgres:18.1
    container_name: origin-db
    command: postgres -c 'max_connections=250'
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: db
      POSTGRES_USER: db
      POSTGRES_DB: db
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5430:5432
  redis:
    image: redis:8.2-alpine
    container_name: origin-redis
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    restart: unless-stopped
    ports:
      - 6370:6379

volumes:
  postgres:
    name: origin-db
    driver: local
